### ISSUE TITLE
feat : Post Model CRUD

### ISSUE THREAD

**Issue by dustin-kang** [dustin-kang/heart-tree#4]
### Board
- Board 모델을 생성
- Board를 CRUD할 수 있는 뷰를 생성하고 테스트코드를 통해 제대로 실행되는지 확인
- Postman을 통해 원하는 Response를 받는지 확인
- Board 생성 및 수정 삭제가 권한에 맞게 수행되는지 수정

### Comment
- Comment 모델 생성
- Comment를 CRD할 수 있는 뷰를 생성하고 테스트코드를 통해 제대로 실행되는지 확인
- Postman을 통해 원하는 Response를 받는지 확인
- Comment 생성 및 수정 삭제가 권한에 맞게 수행되는지 수정

### Scrap
- Scrap 모델 생성
- Scrap를 CRUD할 수 있는 뷰를 생성하고 테스트코드를 통해 제대로 실행되는지 확인
- Postman을 통해 원하는 Response를 받는지 확인
- Scrap 생성 및 수정 삭제가 권한에 맞게 수행되는지 수정

## 📝 Todo
- [x] Scrap, Board 모델 생성
- [x] Board를 CRUD 할 수 있는 뷰 생성
- [x] Comment 모델 생성
- [x] Comment CRD할 수 있는 뷰를 생성
